# Generated by Django 2.2.10 on 2021-06-10 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_tweet_tweet_handle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='tweet_location',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
