# Generated by Django 2.2.10 on 2021-06-10 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20210609_2250'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tweet',
            name='tweet_location',
        ),
        migrations.AddField(
            model_name='tweet',
            name='tweet_location_x',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='tweet',
            name='tweet_location_y',
            field=models.CharField(max_length=25, null=True),
        ),
    ]
