# Generated by Django 2.2.10 on 2021-06-10 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20210610_0134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='tweet_location_x',
            field=models.DecimalField(decimal_places=15, max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='tweet',
            name='tweet_location_y',
            field=models.DecimalField(decimal_places=15, max_digits=18, null=True),
        ),
    ]
